# Generated by Django 5.0 on 2023-12-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markerName', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('pollutionLevel', models.CharField(choices=[('smallTrash', 'Мелкий мусор'), ('largeTrash', 'Крупный мусор'), ('dump', 'Свалка')], max_length=20)),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
