# Generated by Django 5.0 on 2023-12-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='marker',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
