# Generated by Django 5.0 on 2023-12-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_marker_latitude_marker_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='marker',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
