# Generated by Django 5.0 on 2023-12-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_marker_latitude_alter_marker_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='latitude',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='marker',
            name='longitude',
            field=models.TextField(),
        ),
    ]
