# Generated by Django 5.0 on 2023-12-21 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_marker_latitude_alter_marker_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=200, unique=True)),
                ('userPassword', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='marker',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.user', to_field='userName'),
            preserve_default=False,
        ),
    ]
